name: Deploy Explorers

on:
  push:
    branches: [main]
    tags: [v*]

  pull_request:
    branches: [main]

  workflow_dispatch:
    branches: [main]

jobs:

  build-docker-image:
    runs-on: ubuntu-latest

    outputs:
      image-version: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: archwaynetwork/archwayd
          tags: |
            type=semver,pattern={{raw}}
            type=sha


      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-constantine:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && endsWith(github.ref, github.event.repository.default_branch) }}

    needs:
      - build-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_SHARED_NONPROD_EXPLORERS_KUBECONFIG }}
          command: apply -n explorers -f ci/constantine-1-bigdipper.yaml

  deploy-titus:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && endsWith(github.ref, github.event.repository.default_branch) }}

    needs:
      - build-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_SHARED_NONPROD_EXPLORERS_KUBECONFIG }}
          command: apply -n explorers -f ci/titus-1-bigdipper.yaml

  deploy-torii:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' && endsWith(github.ref, github.event.repository.default_branch) }}

    needs:
      - build-docker-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy Chain
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.GKE_SHARED_NONPROD_EXPLORERS_KUBECONFIG }}
          command: apply -n explorers -f ci/torii-1-bigdipper.yaml
